"""Report generation tool for structured climate intelligence output."""
from __future__ import annotations

import json
from datetime import datetime
from langchain_core.tools import tool

@tool
def report_generator(input_data: str) -> str:
    """Generate a structured climate report. Input should be a JSON string
    containing location, risk_level, confidence, analysis, and recommendations.
    """
    try:
        data = json.loads(input_data) if isinstance(input_data, str) else input_data
    except (json.JSONDecodeError, TypeError):
        return "Error: input must be valid JSON"

    location = data.get("location", "Unknown")
    risk = data.get("risk_level", "UNKNOWN")
    confidence = data.get("confidence", "N/A")
    analysis = data.get("analysis", "No analysis provided")
    recs = data.get("recommendations", [])

    report = {
        "report_id": f"RPT-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}",
        "generated_at": datetime.utcnow().isoformat(),
        "title": f"Climate Intelligence Report — {location}",
        "location": location,
        "risk_level": risk,
        "confidence": confidence,
        "executive_summary": analysis,
        "recommendations": recs,
        "disclaimer": (
            "This report is generated by an AI multi-agent system. "
            "Verify critical decisions with local authorities."
        ),
    }
    return json.dumps(report, indent=2)
